### PR TITLE
Update composer.json to use alpha version of omnipay/common

### PR DESCRIPTION
**Pull request by dpfaffenbauer**
This relates to https://github.com/thephpleague/omnipay-common/issues/146, as I am going to migrate Payum OmnipayBridge, I need to have this to use the latest alpha as well.

### CODE REVIEW

**Comment by eimantaspu** [comment]
+1

**Comment by dpfaffenbauer** [comment]
@amacneil any feedback on this one?

**Comment by barryvdh** [comment]
@dpfaffenbauer I'm the maintainer now.

**Comment by dpfaffenbauer** [comment]
thanks for merging 👍 

Could you release version 3.0-alpha then? 

as mentioned here: https://github.com/Payum/Payum/issues/675: as soon as alpha 3 of this gets released, I can created a PR for payum-core and payum-omnipay-bridge to be compatible with the 3.0 branch.

**Comment by barryvdh** [comment]
Done!

**Comment by dpfaffenbauer** [comment]
🍻 cheers 😄

**Pull request merged**
